services:
  web:
    build: ./AppWeb
    container_name: appWeb
    ports:
      - "5000:5000"
    volumes:
      - db-volume:/shared/instance
    environment:
      - DATABASE_URL=sqlite:///Utilisateur.db
      - EMAIL_USER=cryptofrontiersnotif@gmail.com
      - EMAIL_PASSWORD=wgks xsao gjkx npqq 
      - SECRET_KEY=your_secret_key
      - DB_PATH=/shared/instance/Crypto.db
    networks:
      - flask-net

  console:
    build: ./AppConsole
    container_name: appConsole
    ports:
      - "8080:8080"
    volumes:
      - db-volume:/shared/instance
    environment:
      - DB_PATH=/shared/instance/Crypto.db
    restart: always
    networks:
      - flask-net

networks:
  flask-net:
    driver: bridge

volumes:
  db-volume:
    driver: local

