services:
  web:
    build: .
    container_name: webapp
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development 
    networks:
      - flask-net

networks:
  flask-net:
    driver: bridge
