name: Flask Locust Tests

on:
  push:
    branches:
      - main

jobs:
  locust-test:
    name: Run Locust Tests with Flask
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python and install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install locust

      - name: Verify Locust installation
        run: locust --version

      - name: Start Flask, run Locust tests, and stop Flask
        run: |
          nohup python run.py & echo $! > flask_pid
          sleep 5
          locust -f locustWeb.py --headless -u 10 -r 2 --run-time 1m --host=http://127.0.0.1:5000 --csv=locust_report
          kill $(cat flask_pid)
        env:
          FLASK_APP: run.py
          FLASK_ENV: production

