name : SonarQubeConsole

on:
  push:
    branches:
      - appliConsole
jobs:
  sonarqube:
    name: Run SonarQubeConsole Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: ''

      - name: Cache SonarQube scanner
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}

      - name: Run SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          projectKey: 'ProjetGla'
